### ISSUE TITLE
Make ApiHelper raise an exception for 500 response codes

### ISSUE THREAD

**Issue by cameronshinn** [csgo-league/csgo-league-bot#19]
This component currently isn't working [here](https://github.com/csgo-league/csgo-league-bot/blob/0bbbc37baed22aa8101d0109ab41840b328d5f12/bot/helpers/api.py#L175).

**Comment by B3none** [comment]
We should also look at logging exceptions to an error log

**Comment by cameronshinn** [comment]
> We should also look at logging exceptions to an error log

Yeah we can worry about that in a separate issue when we try to spiff up logging. I have that on the bot project board for now.
