### ISSUE TITLE
Unicode characters in team player names are displaying as escaped hex values in-game

### ISSUE THREAD

**Issue by cameronshinn** [csgo-league/csgo-league-bot#25]
#24 is attempting to solve the issue with unicode characters in Discord usernames by preventing players with names including unicode characters from joining the queue. Turns out that the aiohttp [`ClientSession`](https://docs.aiohttp.org/en/stable/client_reference.html?highlight=session#aiohttp.ClientSession) is converting the request JSON payload data to ASCII in the [`start_match()`](https://github.com/csgo-league/csgo-league-bot/blob/ffe3a1ab7908eb40e05afa831bf6e6d696a16db3/bot/helpers/api.py#L235) API helper function. A better fix would be to change the JSON encoder of the `ClientSession` to convert JSON data to unicode instead of ASCII.

**Comment by thboss** [comment]
we can just convert name which is decoded to Unicode [here](https://github.com/splewis/get5/blob/8890db87689cb17d841fc8baae7e3cf061c30c2f/scripting/get5/teamlogic.sp#L376)
same idea [here](https://www.online-toolz.com/tools/text-unicode-entities-convertor.php)

**Comment by cameronshinn** [comment]
The issue isn't with get5, this is an issue with the bot. The aiohttp Python library which we use to interface with our League CS:GO API is converting the player names in the JSON from unicode to ASCII. Like that example you showed me where `'Ð å ń G è R'` is converted to `'\u00d0 \u00e5 \u0144 G \u00e8 R'`. This conversion happens when the dictionary object is being converted to a string for the request payload.

**Comment by cameronshinn** [comment]
Closing with 7cc398aa7a4f15f5577b8885f0f56a3786214a74 merged
