### ISSUE TITLE
Add to Discord bot some command like q!ban @user #time

### ISSUE THREAD

**Issue by 39ma** [csgo-league/csgo-league-bot#8]
After ban feature will go to release: [link](https://github.com/csgo-league/csgo-league-web/commit/cfa2fbea4be877f280e8fa0af2c1f3bcae9b57d9)
it would be good if you could add to Discord bot some command like q!ban @user #time

**Comment by B3none** [comment]
https://github.com/csgo-league/csgo-league-web/blob/develop/app/Router.php#L59
https://github.com/csgo-league/csgo-league-web/blob/develop/app/Router.php#L60

Here's the endpoints you can use, you'll also need to add a check when people join the queue if you don't already have one :)

**Comment by cameronshinn** [comment]
Is there an endpoint where I can check if a user is banned? Does "banning" make it so they can't join League servers? If I am able to check if they are banned then I can prevent them from joining the queue and wasting everyone's time when it pops and the banned user cannot join the server.

**Comment by B3none** [comment]
They're here @cameronshinn https://github.com/csgo-league/csgo-league-bot/issues/8#issuecomment-612357649
